require("modules.lazy")
require("modules.lsp")
require("modules.cmp")
require("modules.format")
require("modules.lint")
require("modules.dap")
require("modules.treesitter")
require("modules.telescope")
require("modules.notify")
require("modules.colorscheme")
require("modules.lualine")
require("modules.alpha")
require("modules.rundi")
require("modules.mkdnflow")
require("modules.clip")

-- convert all of em into opts
require("Comment").setup({})
require("nvim-surround").setup({})
require("colorizer").setup({})
require("tmux").setup({})
