require("modules.pack")
require("modules.lualine")
require("modules.comment")
require("modules.colorizer")
require("modules.telescope")
require("modules.vimwiki")
require("modules.dashboard")
require("modules.cmp")
